Repository tryber/sd-07-project-frontend-online-store, pull requests merged in 2020-11, with the labels that each got.

#39 Iniciando projeto
  src/App.js
  src/services/api.js
Labels: Code Review

#26 Request API
  package-lock.json
  package.json
  src/App.js
  src/Components/Search.js
  src/index.js
  src/services/api.js
Labels: Code Review

#52 [Group-39] CRIAR PÁGINA DO CARRINHO DE COMPRAS
  package-lock.json
  src/App.js
  src/PageCard.jsx
  src/ProductList.jsx
  src/shopping-cart2.jpg
  src/shoppingCartImage.png
Labels: Code Review

#33 [GRUPO 21] - Requisito 1 - adicionando API
  .gitignore
  src/services/api.js
Labels: Code Review

#27 [GRUPO 21] Cria tela de busca
  package-lock.json
  package.json
  src/App.js
  src/components/ProductList.jsx
Labels: Code Review

#49 [GROUP 05] Feito react router no App.js
  package-lock.json
  package.json
  src/App.js
  src/pages/Checkout.js
  src/pages/NotFound.js
  src/pages/ProductDetails.js
  src/pages/ProductsList.js
  src/pages/ShoppingCart.js
  src/pages/index.js
Labels: Code Review

#71 [ GRUPO 6 ] Adicionando APIs do Mercado Livre
  src/App.js
  src/services/api.js
Labels: Code Review

#50 [GROUP 5] Implementa módulo de acesso à API do Mercado Livre
  .github/workflows/main.yml
  src/services/api.js
Labels: Code Review

#23 Acesso api
  README.md
  package-lock.json
  src/services/api.js
Labels: Code Review

#92 [GRUPO 20] Implementaçao do modulo que acessa a API
  .github/workflows/main.yml
  src/services/api.js
Labels: Code Review

#111 implementação da API
  src/App.js
  src/services/api.js
Labels: Code Review

#40 [Grupo 10] Adicionando página ProductList vazia
  src/App.js
  src/components/ProductList.js
Labels: Code Review

#112 Finalizadas as duas funções de requisição a API do meli
  .github/workflows/main.yml
  src/services/api.js
Labels: Code Review

#98 [GRUPO 17] Requisito 3 - Criando botão e página do carrinho de compras
  public/images/Cart-Icon.svg
  public/images/Shopping-Cart-icon.png
  src/App.js
  src/components/CartButton.js
  src/pages/ProductList.js
  src/pages/ShoppingCart.js
Labels: Code Review

#127 [Grupo 8] Botão do carrino de compras
  package-lock.json
  src/App.css
  src/App.js
  src/Components/ButtonCart.js
  src/Components/Search.js
Labels: Code Review

#133 [GRUPO 26] Criado campo de busca inicial vazio
  src/App.js
Labels: Code Review

#143 [Grupo 21] requisito 03 botão do carrinho
  src/App.js
  src/components/ProductList.jsx
  src/components/cartButton.jsx
Labels: Code Review

#145 [GRUPO 21] - Requisito 4 - listando categorias na tela da API
  package.json
  src/App.css
  src/App.js
  src/components/CategoryList.jsx
  src/components/ProductList.jsx
Labels: Code Review

#167 Main group 8 create product list
  .github/workflows/main.yml
  src/App.css
  src/Components/Search.js
Labels: Code Review

#208 [GRUPO 21]Listagem de produtos
  src/components/Product.jsx
  src/components/ProductList.jsx
  src/services/api.js
Labels: Code Review

#138 [Grupo 10] Adicionado um botao e a mensagem "Seu carrinho está vazio"
  package-lock.json
  package.json
  src/App.js
  src/components/ProductList.js
  src/components/ShoppingCart.js
Labels: Code Review

#203 [Grupo 10] Lista de categorias
  src/App.js
  src/components/CategoryList.js
Labels: Code Review

#236 Main group 39 requisito 5 alteracoes
  src/pages/ProductsList.jsx
  src/services/api.js
Labels: Code Review

#240 [GROUP 39] Feitas alterações na exibição das listas
  src/App.js
  src/components/CategorieItem.jsx
  src/components/CategoriesList.jsx
  src/components/Product.jsx
  src/pages/PageCard.jsx
  src/pages/ProductsList.jsx
  src/services/api.js
Labels: Code Review

#218 [GRUPO 35] Lista de produtos
  src/components/ProductList.jsx
  src/components/SearchBar.jsx
Labels: Code Review

#129 [GRUPO 35] Botão Shopping Cart - Placeholder
  package-lock.json
  package.json
  src/App.js
  src/components/ShoppingCart.jsx
Labels: Code Review

#130 Main group 17 requirement 4
  src/components/CategoryList/index.js
  src/pages/ProductList/index.js
Labels: Code Review

#146 [Grupo 25] Requisito 03
  package.json
  src/App.js
  src/components/ProductsList.js
  src/components/ShoppingCartButton.js
  src/icons/IconShoppingCart.js
  src/pages/ShoppingCart.js
  src/services/api.js
Labels: Code Review

#220 [ GRUPO 6 ] Requisito 3 - Página do carrinho de compras
  src/App.js
  src/pages/Cart.jsx
  src/pages/Home.jsx
Labels: Code Review

#164 [Grupo 25] Requisito 04
  src/App.js
  src/components/CategoryList.js
  src/components/ItemCategory.js
Labels: bug

#202 Main group 26 botao shoppingcart
  package-lock.json
  src/App.js
  src/images/CartIcon.png
  src/pages/home.js
  src/pages/shoppingCart.js
Labels: Code Review

#228 [ GRUPO 06 ] Criando Lista de Categorias - Requisito 04
  src/App.css
  src/App.js
  src/components/ItemCategory.jsx
  src/components/ListCategory.jsx
  src/components/Loading.jsx
  src/pages/Home.jsx
Labels: Code Review

#259 [Main group 8] Listagem dos produtos pelo termo retorno da API
  src/App.css
  src/Components/Search.js
Labels: Code Review

#162 [GROUP 5] Acesso a API ML
  .eslintrc.json
  src/services/api.js
Labels: Code Review

#252 [GRUPO 5] Arrumando o CC
  package-lock.json
  src/App.js
  src/components/FilteredProductsList.js
  src/components/Loading.js
  src/components/SearchBar.js
  src/pages/Checkout.js
  src/pages/ProductDetails.js
  src/pages/ProductsList.js
  src/pages/ShoppingCart.js
Labels: Code Review

#275 [Main group 8] Enviando Arquivos criados
  src/Components/CardList.js
  src/Components/CardProduct.js
  src/Components/DigiteTermo.js
  src/Components/ListAllProducts.js
  src/Components/ProductDetails.js
  src/Components/ProductNotFound.js
Labels: Code Review

#192 [GRUPO 24 - Tropa de ESLint :hocho: :skull: ] Resolvendo o Requisito 03
  src/App.js
  src/ProductList.jsx
  src/ShoppingCartList.jsx
  src/shopping-cart.png
Labels: Code Review

#274 [Grupo 24] Requisito 04
  src/App.css
  src/CategoriesList.jsx
  src/CategoryItem.jsx
  src/ProductList.jsx
Labels: Code Review

#212 [GRUPO 24 - Tropa de ESLint] Resolvendo o Requisito 05 e ajustando a api (req1)
  src/ProductList.jsx
  src/services/api.js
Labels: Code Review

#280 [GROUP 39] Finalizado requisito 6
  src/components/CategoriesList.jsx
  src/components/ShowProducts.jsx
  src/pages/ProductsList.jsx
  src/services/api.js
Labels: Code Review

#291 Group 5 shopping cart
  src/components/SearchBar.js
  src/pages/ShoppingCart.js
Labels: Code Review

#306 [Grupo 40] Requito 2 v1.0
  package-lock.json
  package.json
  src/App.js
  src/pages/Home.js
Labels: Code Review

#310 [GRUPO 39] Requisito 7 - CLICAR NA EXIBIÇÃO RESUMIDA DE UM PRODUTO E IR PARA UMA TELA COM SUA EXIBIÇÃO DETALHADA
  src/App.js
  src/components/CategoriesList.jsx
  src/components/Product.jsx
  src/components/ShowProducts.jsx
  src/pages/ProductDetail.jsx
  src/services/api.js
Labels: Code Review

#314 [Group 26] listagem produtos
  src/images/lupa.png
  src/pages/ProductCard.js
  src/pages/SearchBar.js
  src/pages/home.js
Labels: Code Review

#294 [ GRUPO 6 ] Listagem de produtos
  src/components/CardProduct.jsx
  src/components/ListCategory.jsx
  src/pages/Home.jsx
  src/services/api.js
Labels: Code Review

#324 [Grupo 25] - Requisito 5 (refatorado)
  src/components/ProductCard.js
  src/components/ProductsList.js
  src/components/SearchBar.js
  src/pages/Products.js
Labels: Code Review

#284 [Group 13] Criado de forma generalizada o componente button
  src/App.js
  src/components/forms/Button/index.js
  src/components/forms/Button/style.js
Labels: Code Review

#264 [Group 22] requisito 4 by Rodrigo
  src/pages/listagem.jsx
  src/services/api.js
Labels: Code Review

#320 [GRUPO 24 - Tropa de ESLint] Resolvendo Requisito 06
  src/CategoriesList.jsx
  src/CategoryItem.jsx
  src/ProductList.jsx
Labels: Code Review

#357 [GRUPO 24 - Tropa de ESLint] Organização do projeto - boas práticas
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/CategoriesList.jsx
  src/CategoryItem.jsx
  src/ProductList.jsx
  src/components/CategoryList/CategoryList.css
  src/components/CategoryList/index.js
  src/components/EvaluationForm/index.js
  src/components/EvaluationList/index.js
  src/components/ProductCard/index.js
  src/components/ProductImage/index.js
  src/components/ProductList/index.js
  src/components/ProductSummary/index.js
  src/components/QuantityControl/index.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/index.js
  src/components/SearchBar/shopping-cart.png
  src/components/ShoppingCartList/index.js
  src/components/index.js
  src/index.js
  src/logo.svg
  src/pages/Home/Home.css
  src/pages/Home/index.js
  src/pages/ProductDetail/index.js
  src/pages/ShoppingCart/index.js
  src/pages/index.js
  src/routes/index.js
  src/services/api.js
Labels: Code Review

#293 [Grupo 35] Requisito 07 - Adição da funcionalidade de clique para abrir a página de mais detalhes
  src/App.js
  src/components/ProductList.jsx
  src/pages/ProductDetails.jsx
  src/style/productList.css
Labels: Code Review

#305 [Grupo 15]Busca pela barra de categorias
  src/pages/CategoriesList.js
  src/pages/Home.js
Labels: Code Review

#371 [GRUPO 24] Complementando o Requisito 05 - Component Product Card
  src/components/ProductCard/ProductCard.css
  src/components/ProductCard/index.js
  src/components/ProductList/index.js
  src/pages/Home/Home.css
Labels: Code Review

#302 Group5 requirement 4
  package-lock.json
  src/components/ListCategory.js
  src/pages/ProductsList.js
  src/services/api.js
Labels: Code Review

#343 GRUPO 17 - Requerimento 7
  src/App.js
  src/components/Card/index.js
  src/pages/ProductDetails/index.js
  src/pages/ProductList/index.js
Labels: Code Review

#363 [Group 6]Main group 6 css
  src/App.css
  src/components/CardProduct.jsx
  src/components/Loading.jsx
  src/pages/Cart.jsx
  src/pages/Home.jsx
Labels: Code Review

#385 Requisito 9
  src/pages/PageCard.jsx
  src/pages/ProductDetail.jsx
  src/pages/ProductsList.jsx
Labels: Code Review

#196 [ group 20] implementa requisito 5
  .github/workflows/main.yml
  src/App.js
  src/ShoppingCart.js
  src/components/CategoriesList.js
  src/components/Home.jsx
  src/components/ProductCard.js
  src/components/ProductList.js
  src/components/ProductsList.js
  src/services/api.js
Labels: Code Review

#401 [GROUP 28] [PRIORITY 3] [REQUIREMENT 7] [PRODUCT DETAILS]
  package-lock.json
  src/components/Loading/Loading.css
  src/components/Loading/Loading.jsx
  src/components/ProductCard/ProductCard.jsx
  src/pages/ProductDetails.jsx
  src/router.js
Labels: Code Review

#360 [GRUPO 24] Requisito 07
  .github/workflows/main.yml
  src/components/ProductCard/index.js
  src/index.js
  src/pages/Home/index.js
  src/pages/ProductDetail/ProductDetail.css
  src/pages/ProductDetail/index.js
  src/routes/index.js
Labels: Code Review

#410 [GRUPO 39] Requisito 11 - AVALIAR E COMENTAR ACERCA DE UM PRODUTO EM SUA TELA DE EXIBIÇÃO DETALHADA
  .github/workflows/main.yml
  src/pages/ProductDetail.jsx
  src/pages/ProductsList.jsx
Labels: Code Review

#408 [GRUPO 25] - Requisito 07
  src/App.js
  src/components/ProductAttributes.js
  src/components/ProductCard.js
  src/pages/ProductDetails.js
Labels: Code Review

#411 [GROUP 39] requisito 8
  src/App.js
  src/components/CartItem.jsx
  src/components/Product.jsx
  src/logo.svg
  src/pages/ProductDetail.jsx
Labels: Code Review

#422 Requisito 07 Renderizando um produto - 26/11/2020
  src/App.js
  src/components/CardProduct.jsx
  src/components/ItemCategory.jsx
  src/components/ListCategory.jsx
  src/images/lupa.png
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
Labels: Code Review

#428 Main group 17 requirement 9
  src/components/Card/index.js
  src/components/CategoryList/index.js
  src/pages/ProductList/index.js
  src/pages/ShoppingCart/index.js
Labels: Code Review

#492 [GROUP 39] requisito10 v4
  src/components/CartItem.jsx
  src/components/Product.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
Labels: Code Review

#469 [Grupo 10] Requisito 10 -> Quantidade do produtos na aba ShoppingCart.js
  src/components/ShoppingCart.js
Labels: Code Review

#497 [Grupo 32] Main-group-32 adjustments
  package-lock.json
  src/App.css
  src/App.js
  src/components/Categories.js
  src/components/Home.js
  src/components/ProductList.js
  src/components/SearchBar.js
  src/components/index.js
  src/pages/Home.js
  src/pages/ProductDetails.js
  src/pages/ShoppingCart.js
  src/pages/index.js
Labels: Grupo32

#464 Grupo 17 - Requerimento 10
  src/components/CartItem/index.js
  src/pages/ShoppingCart/index.js
  src/services/cartApi.js
Labels: Code Review

#448 [Grupo 25] - Requisito 11
  package-lock.json
  package.json
  src/components/RatingForm.js
  src/pages/ProductDetails.js
  src/services/ratingAPI.js
Labels: Code Review

#496 [GROUP 39] Adicionada funções para somar e subtrair itens
  src/components/Product.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
Labels: Code Review

#505 [Grupo 10] problema das quantidade dos carrinhos resolvida
  src/components/ShoppingCart.js
Labels: Code Review

#507 Adicionado botão para remover item do carrinho
  src/components/CartItem.jsx
  src/pages/ShoppingCart.jsx
Labels: Code Review

#512 [ Main group 32 ] adicionando requisitos 5 e 6
  package-lock.json
  package.json
  src/App.js
  src/__tests__/requirement10.test.js
  src/__tests__/requirement11.test.js
  src/__tests__/requirement12.test.js
  src/__tests__/requirement13.test.js
  src/__tests__/requirement14.test.js
  src/__tests__/requirement15.test.js
  src/__tests__/requirement7.test.js
  src/__tests__/requirement8.test.js
  src/__tests__/requirement9.test.js
  src/components/Categories.js
  src/components/ProductCard.js
  src/components/ProductList.js
  src/components/SearchBar.js
  src/components/ShoppingCart.js
  src/pages/Home.js
  src/pages/ProductsList.js
  src/pages/ShoppingCart.js
  src/pages/index.js
  src/services/api.js
Labels: Grupo32

#520 Main group 10 form product details
  src/components/ProductDetails.js
  src/components/ProductEvaluationForm.js
Labels: Code Review

#431 [Grupo 24] Requisito 08
  src/components/ProductCard/index.js
  src/components/ProductList/index.js
  src/components/SearchBar/index.js
  src/components/ShoppingCartList/index.js
  src/pages/Home/index.js
  src/pages/ShoppingCart/index.js
  src/services/lsapi.js
Labels: Code Review

#516 [GROUP 28][Issues GitHub Actions and PropTypes]
  package-lock.json
  src/components/CategoryList/CategoryList.jsx
  src/components/ProductCard/ProductCard.jsx
  src/components/ShoppingCartButton/ShoppingCartButton.jsx
  src/pages/HomePage.jsx
  src/pages/ProductDetails.jsx
Labels: Code Review

#522 [GROUP 26] Product Detail
  src/App.css
  src/App.js
  src/pages/ProductCard.js
  src/pages/ProductDetail.js
  src/services/api.js
Labels: Code Review

#494 [Grupo 25] Requisito 9
  src/components/ProductAttributes.js
  src/components/ShowCartItems.js
  src/pages/ProductDetails.js
  src/pages/ShoppingCart.js
  src/services/localStorageHandler.js
Labels: Code Review

#537 [GRUPO 39] Requisito 12 - FINALIZAR COMPRA, VENDO UM RESUMO DELA, PREENCHENDO OS MEUS DADOS E ESCOLHENDO A FORMA DE PAGAMENTO
  src/App.js
  src/components/CartItem.jsx
  src/pages/Checkout.jsx
  src/pages/ProductDetail.jsx
  src/pages/ShoppingCart.jsx
Labels: Code Review

#550 Main group 39 requisito 13
  src/components/CartIcon.jsx
  src/components/Product.jsx
  src/components/ShowProducts.jsx
  src/pages/ProductDetail.jsx
  src/pages/ProductsList.jsx
Labels: Code Review

#479 [Grupo 15] Product details feedback
  package-lock.json
  src/pages/CategoriesList.js
  src/pages/Home.js
  src/pages/ProductDetails.jsx
  src/services/localStorage.jsx
Labels: Code Review

#528 [GRUPO 24 ] Requisito 11
  package-lock.json
  package.json
  src/components/EvaluationForm/EvaluationForm.css
  src/components/EvaluationForm/index.js
  src/components/EvaluationList/EvaluationList.css
  src/components/EvaluationList/index.js
  src/pages/ProductDetail/index.js
  src/services/lsapi.js
Labels: Code Review

#614 [GROUP 39] coitado do requisito 15
  src/components/Product.jsx
  src/components/ShowProducts.jsx
  src/pages/ProductDetail.jsx
  src/pages/ProductsList.jsx
  src/pages/ShoppingCart.jsx
Labels: Code Review

#619 [ GRUPO 6 ] AVALIAR E COMENTAR ACERCA DE UM PRODUTO EM SUA TELA DE EXIBIÇÃO DETALHADA
  src/components/Assessment.jsx
  src/components/ProductDetailsEvaluation.jsx
  src/pages/Home.jsx
  src/pages/ProductDetails.jsx
Labels: Code Review

#581 [Grupo 25] Resolução de conflito entre requisitos 8 e 9
  src/components/ProductCard.js
  src/components/ShowCartItems.js
  src/pages/ProductDetails.js
  src/pages/ShoppingCart.js
Labels: Code Review

#526 [Grupo 32] - Requisito 7
  src/App.css
  src/App.js
  src/__tests__/requirement7.test.js
  src/components/Categories.js
  src/components/ProductCard.js
  src/pages/Home.js
  src/pages/ProductDetails.js
  src/services/api.js
Labels: Grupo32

#664 [GROUP 39] Requisito 18
  src/pages/ProductsList.jsx
Labels: Code Review

#667 [GROUP 39] item selecionado
  src/components/Product.css
  src/components/Product.jsx
  src/pages/ProductsList.jsx
Labels: Code Review

#674 [Groupo 31] Add produto ao carrinho
  src/components/ButtonAddShoppingCart.js
  src/components/Products.js
  src/pages/ShoppingCartPage.js
Labels: Code Review

#690 [Main-Group-32] - Requisito 8
  src/App.js
  src/__tests__/requirement8.test.js
  src/components/ProductCard.js
  src/components/ProductCartItems.js
  src/components/ProductCartList.js
  src/components/ShoppingCart.js
  src/pages/Home.js
  src/pages/ProductsList.js
Labels: Grupo32

#685 [GRUPO 24] Requisito 12
  src/components/BuyerInformation/index.js
  src/components/PaymentOption/PaymentOption.css
  src/components/PaymentOption/barcode.png
  src/components/PaymentOption/creditcard.png
  src/components/PaymentOption/index.js
  src/components/ProductCard/index.js
  src/components/QuantityControl/index.js
  src/components/ShoppingCartList/index.js
  src/components/index.js
  src/pages/Checkout/Checkout.css
  src/pages/Checkout/index.js
  src/pages/ShoppingCart/index.js
  src/pages/index.js
  src/routes/index.js
Labels: Code Review

#689 [Grupo 35] Adicionar um produto ao carrinho a partir de sua tela de exibição detalhada
  src/pages/ProductDetails.jsx
Labels: Code Review

#709 [GRUPO 25] Requisito 12
  src/App.js
  src/components/ListItem.js
  src/components/UserInfoForm.js
  src/data/estadosBrasileiros.js
  src/pages/Payment.js
  src/pages/ShoppingCart.js
Labels: Code Review

#711 [Grupo 32] - Requisito 11
  src/App.css
  src/__tests__/requirement11.test.js
  src/index.css
  src/pages/ProductDetails.js
Labels: Grupo32

#710 Main group 17 requirement 12
  src/App.js
  src/pages/Checkout/index.js
  src/pages/ShoppingCart/index.js
Labels: Code Review
